name: Bug Report
description: "Please write your reports in the [Discussions section](https://github.com/FakeFishGames/Barotrauma/discussions/categories/bug-reports), and please look for and upvote reports about issues similar to yours."
body:
  - type: markdown
    attributes:
      value: |
Please write your reports in the [Discussions section](https://github.com/FakeFishGames/Barotrauma/discussions/categories/bug-reports) from now on, and please look for and upvote reports about issues similar to yours.
